### ISSUE TITLE
Adding Crime index feature "Crime Index"

### ISSUE THREAD

**Issue by roprashar** [place2live/place2live#140]
**Describe the solution you'd like**
Good to have crime index for each country .

**Comment by serhii73** [comment]
Hello. We can extract information from here http://worldpopulationreview.com/countries/crime-rate-by-country/
Country name and place in this rating. Not index.
But I think it not necessary because we extracted the crime index from numbeo data already.
But if you think it is a good idea to add new column in the result table - we can to add it.

**Comment by serhii73** [comment]
What do you think about that @roprashar ?

**Comment by roprashar** [comment]
yes , we can add new column, additionally we can add feature in case country name entered wrong by user then show with the message the closest country name by match alphabets , ex : user entered Autalia, then message comes: did u mean Australia or Austria

**Comment by roprashar** [comment]
if its oki ? , then i can take care of these features .

**Comment by serhii73** [comment]
It's a very good idea.
Thank you very much!

**Comment by roprashar** [comment]
closest match func i already added . :)
